spring:
  application:
    name: demo

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/ilm_app?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345Gulo

  main:
    allow-bean-definition-overriding: true


jwt:
  secret: XQzVcDZs7KtEQ9ZPjAeTRWnPSNmX/mQpg7WvB5uYOjQ=
  expiration: 86400000 # Access token: 1 gün (milisaniye cinsinden)
  refresh-token:
    expiration: 604800000 # Refresh token: 7 gün (milisaniye cinsinden)



logging:
  level:
    org.springframework.security: trace

server:
  port: 8080

